### ISSUE TITLE
🐛 [BUG] - Accessory Device name is wrong

### ISSUE THREAD

**Issue by Mittelblut9** [Mittelblut9/ioBroker.apple-find-me#53]
### Description

Currently the Accessory Device name is set to "Some Device Name". This may happen if the accessory device name is somewhere else located or the assignment is false. 

https://github.com/Mittelblut9/ioBroker.apple-find-me/blob/8f325d450b9598db0bfaee7e7771ae053cc2dd3d/src/functions/Adapter/createOrUpdateDevices.js#L44C29-L44C29

### Reproduction steps

```bash
1. import devices with accessory like an AirPods
2. view objects
```

### Screenshots

![image](https://github.com/Mittelblut9/ioBroker.apple-find-me/assets/67608550/83b2348d-410d-498c-b8b5-792bb57c7f21)

**Comment by Ilovegym66** [comment]
![image](https://github.com/Mittelblut9/ioBroker.apple-find-me/assets/36229898/950525b2-a813-43c4-b47e-5eac77ffa47b)
